### ISSUE TITLE
Unable to join multiplayer: java.lang.IllegalStateException: Rendersystem called from wrong thread

### ISSUE THREAD

**Issue by WillyJL** [zabi94/NBTTooltip#19]
Full log: [latest.log](https://github.com/zabi94/NBTTooltip/files/6757326/latest.log)

Though looks to me like this is the important part:
```
[00:26:24] [Server Connector #1/ERROR]: Couldn't connect to server
java.lang.IllegalStateException: Rendersystem called from wrong thread
	at Not Enough Crashes deobfuscated stack trace.(1.17+build.13) ~[?:?]
	at com.mojang.blaze3d.systems.RenderSystem.assertThread(RenderSystem:148) ~[fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.client.util.Window.logGlError(Window:222) ~[?:?]
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokePI(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwGetKey(GLFW.java:3409) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at net.minecraft.client.util.InputUtil.isKeyPressed(InputUtil:465) ~[?:?]
	at zabi.minecraft.nbttooltip.NBTTooltip.handleClipboardCopy(NBTTooltip.java:173) ~[nbttooltip-1.3.0-fabric.jar:?]
	at zabi.minecraft.nbttooltip.NBTTooltip.onInjectTooltip(NBTTooltip.java:139) ~[nbttooltip-1.3.0-fabric.jar:?]
	at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:37) ~[575f9b00-0b23-42aa-ba7f-64ead3f5fed1.jar:?]
	at net.minecraft.item.ItemStack.handler$zpn000$getTooltip(ItemStack:2712) ~[?:?]
	at net.minecraft.item.ItemStack.getTooltip(ItemStack:815) ~[?:?]
	at net.minecraft.client.MinecraftClient.method_1485(MinecraftClient:767) ~[?:?]
	at net.minecraft.client.search.TextSearchableContainer.index(TextSearchableContainer:36) ~[?:?]
	at net.minecraft.client.search.IdentifierSearchableContainer.add(IdentifierSearchableContainer:48) ~[?:?]
	at net.minecraft.client.MinecraftClient.method_1535(MinecraftClient:780) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraft.client.MinecraftClient.initializeSearchableContainers(MinecraftClient:779) ~[?:?]
	at net.minecraft.client.MinecraftClient.callInitializeSearchableContainers(MinecraftClient) ~[?:?]
	at net.earthcomputer.multiconnect.protocols.generic.AbstractProtocol.setup(AbstractProtocol.java:59) ~[multiconnect-1.4.4.jar:?]
	at net.earthcomputer.multiconnect.connect.ConnectionHandler.onSendHandshake(ConnectionHandler.java:113) ~[multiconnect-1.4.4.jar:?]
	at net.minecraft.class_412$1.redirect$cdk000$sendHandshake(class_412.java:536) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_412$1.run(class_412.java:78) [intermediary-fabric-loader-0.11.6-1.17.jar:?]
```

These are my keybind settings:

![image](https://user-images.githubusercontent.com/49810075/124333724-5f468800-db95-11eb-90a6-89f8ae704523.png)

And these are my mod settings:

![image](https://user-images.githubusercontent.com/49810075/124334451-5fe01e00-db97-11eb-8034-5e63eb1787a8.png)

**Comment by WillyJL** [comment]
Actually just found out that this fixes itself by adding a keybind for "Copy NBT", though still odd that it only gives problems in multiplayer...

**Comment by WillyJL** [comment]
Also side note but I feel like being able to scroll the nbt with the actual scroll wheel could be a nice addition, just putting this out there...

**Comment by zabi94** [comment]
I considered that at some point, but the scroll wheel is used to transfer items quickly between inventories (or bar/inner player inv) already in most modpacks

**Comment by Felix14-v2** [comment]
> I considered that at some point, but the scroll wheel is used to transfer items quickly between inventories (or bar/inner player inv) already in most modpacks

At least as a disabled by default option? (◕.◕)

**Comment by zabi94** [comment]
It's not really worth it. My free time is now very limited due to work, and I'd rather focus it on key features

**Comment by zabi94** [comment]
If someone feels like doing it themselves as a contribution, I'd gladly merge the change though
